# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
